--- #YAML:1.0
name:               Test-MockClass
version:            1.05
abstract:           A class to create mock classes and object for testing purposes
author:
    - Jeremiah Jordan <jjordan@perlreason.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Hook::WrapSub:     0.03
    Scalar::Util:      1.14
    Task::Weaken:      0
    Test::SimpleUnit:  1.21
    Tie::Watch:        1.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
